config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
scope module: :user do
  root 'homes#top'
  # タグの検索
  get "search_tag"=>"posts#search_tag"
  resources :users, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
  resources :messages, only: [:create,:destroy]
  resources :rooms, only: [:create,:show]
  resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy, :ranking] do
    collection do
      get :search
    end
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
end

get "users/:id/unsubscribe" => "user/users#unsubscribe", as: "unsubscribe"
patch "users/:id/withdraw" => "user/users#withdraw", as: "withdraw"


#ゲストログイン
devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  root 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:index, :show, :destroy] do
    resources :comments, only: [:destroy]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #ゲストログイン
  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #フォローをされた時の関係
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #フォローをしたときの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image, :is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    post_comment = @post.comments.find(params[:id])
    post_comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

  def index
    @user = current_user
    favorites = current_user.favorites.pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def create
    #formで送られてきたroom_idとcurrent_user.idを持ったデータがEntryにあるかを確認
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      #contentとroom_idはformで送られてきているため、user_idをマージして新規メッセージを作成
      @message = Message.create((message_params).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def message_params
      params.require(:message).permit(:user_id, :content, :room_id)
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @post = Post.new
  end

  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    @user = current_user
    @tag_list = Tag.all.limit(10)
    @post_all = Post.all
    if params[:place_id]
      # Post.find([1, 4, 2])
      @favorite_ranks = Post.where(id: Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id), place_id: params[:place_id]).limit(3)
    else
      @favorite_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
    if @post.user == current_user
      render "edit"
    else
      redirect_to post_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list=params[:post][:name].split(',')
    if @post.save
      @post.save_tag(tag_list)
      redirect_to posts_path(@post.id), notice:'投稿しました'
    else
      render:new, notice: '投稿に失敗しました'
    end
  end

  def update
    @post = Post.find(params[:id])
    tag_list=params[:post][:name].split(',')
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post.id), notice: '更新しました'
    else
       render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

 def search_tag
    @tag_list=Tag.all.order(created_at: :desc)
    @tag=Tag.find(params[:tag_id])
    @posts=@tag.posts.page(params[:page]).per(10)
  end

 def search
    keyword = params[:keyword].sub(/　/,' ')  #全角であれば半角にする
    keywordAry = keyword.split(' ')# "ケーキ 青森県" → ["ケーキ", "青森県"]のように、『半角スペースを基準に分割する』
    # @posts = []
    @posts = Post.all
    keywordAry.each do |keyword|
      # @posts.concat(Post.search(keyword))
      @posts = @posts.search(keyword)
    end
    # @posts = @posts.uniq
  end

 private
  def post_params
    params.require(:post).permit(:title, :text, :place_id, :genre_id, :image, :comment)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
   before_action :authenticate_user!

  def create
    @room = Room.create
    # current_userのEntry
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    # DMを受け取る側のEntry（users/showでuser_idは渡しているため、room_idを拾って、マージしている）
    @entry2 = Entry.create((entry_params).merge(room_id: @room.id))
    redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    # entriesテーブルにcurrent_user.idと紐付いたチャットルームがあるかどうか確認
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.order(created_at: :asc)
      @message = Message.new
      # チャットルームのユーザ情報を表示させるため代入
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end



  private
    def entry_params
      params.require(:entry).permit(:user_id, :room_id)
    end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  #ゲストログイン
  def guest_sign_in
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password])
      if @user.is_deleted == true
        redirect_to new_user_registration_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5)
    @post_all = @user.posts
    @favorites = Favorite.where(user_id: current_user.id)
    @currentUserEntry = Entry.where(user_id: current_user.id) # current_userをEntriesテーブルから探す
    @userEntry = Entry.where(user_id: @user.id) # DMを送る対象のユーザーをEntriesテーブルから探す
    if @user.id != current_user.id
      # currentUserと@userのEntriesをそれぞれ一つずつ取り出し、2人のroomが既に存在するかを確認
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
        # 2人のroomが既に存在していた場合
          if cu.room_id == u.room_id
            @isRoom = true
            #room_idを取り出す
            @roomId = cu.room_id
          end
        end
      end
      # 2人ののroomが存在しない場合
      unless @isRoom
        #roomとentryを新規に作成する
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user)
  end

  def unsubscribe
    @user = User.find_by(name: params[:name])
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image, :image)
  end

  def currect_user
    @user = User.find(params[:id])
    @user = @post.user
    redirect_to(root_path) unless @user == current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <h4 class="text-info text-opacity-25">マイページ編集</h4>
  </div>
  <%= form_with model: @user, url: user_path, id: "form" do |f| %>
    <div class="form-group">
      <label for="user_image">プロフィール画像</label>
      <%=f.file_field :profile_image, acoept: "image/*" %>
      <div class="form-group row m-2">
        <label class="col-sm-2 col-form-label">名前</label>
        <div class="col-sm-10">
          <%= f.text_field :name %>
        </div>
        <label class="col-sm-2 col-form-label">自己紹介文</label>
        <div class="col-sm-10">
          <%= f.text_area :introduction %>
        </div>
        <%= f.submit "変更を保存", class:"btn btn-outline-success" %>
        <%= link_to "退会する", unsubscribe_path, class: "btn btn-outline-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/user/users/show.html.erb
<div class="container px-5 px sm-0">
  <div class="row my-5">
    <div class="col-md-4">
    <h2 class="text-info text-opacity-25">マイページ</h2>
      <!-- ユーザーの詳細 -->
      <h4>登録情報</h4>
      <%= image_tag @user.get_profile_image, class: "rounded-circle", size: "150x150"  %>

      <div class="mt-3">
        <label>名前</label>
      </div>
      <div ><%= @user.name %></div>
      <div>
        <label class="mt-2">自己紹介文</label>
      </div>
      <div><%= @user.introduction %></div>
      <div class="mt-3">
        <% if current_user == @user %>
          <% if @user.name != "guestuser" %>
            <%= link_to "編集する", edit_user_path(@user), class: 'btn btn-outline-success' %>
            <%= link_to "いいね一覧︎",favorites_path(@favorites),class: 'btn btn-outline-warning' %>
          <% end %>
        <% end %>
      </div>
      <% if @user.id != current_user.id %>
        <!--既にroomがある場合（以前にDMのやりとりしている）-->
        <% if @isRoom == true %>
          <%= link_to "DMする", room_path(@roomId) %>
        <!--roomがない場合-->
        <% else %>
          <!--RoomとEntry2つのモデルにデータを送る-->
          <%= form_with model:@room, local: true do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value=> @user.id %>
            <% end %>
            <%= f.submit "チャットを始める" %>
          <% end %>
        <% end %>
      <% end %>
  　</div>

    <div class = "col-md-8">
      <!-- ユーザーの投稿一覧 -->
      <h2 class="text-info text-opacity-25">投稿一覧</h2>
      <p>< <%=@posts.count %>件 / 全<%= @post_all.count %>件の投稿 ></p>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th class="border-dark table-active">投稿画像</th>
              <th class="border-dark table-active">タイトル</th>
              <th class="border-dark table-active">投稿文</th>
              <th class="border-dark table-active">コメント</th>
              <th class="border-dark table-active">いいね</th>
            </tr>
          </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                  <%= image_tag post.get_image, size: "100x100" %>
              </td>
              <td><%= link_to post_path(post.id) do %><%= post.title.truncate(10) %><% end %></td>
              <td><%= post.text.truncate(10) %></td>
              <td><%= link_to "#{post.comments.count}件", post_path(post.id) %></td>
              <td id='favorite_buttons_<%= post.id %>'>
                <%= render 'user/favorites/favorites', post: post%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div><%= paginate @posts %></div>
    </div>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class="container">
  <div class="text-center mt-4">
    <h2><strong>本当に退会しますか？</strong></h2>
  </div>

  <div class="text-center mt-5 mb-5">
    <p>
      退会する場合は、「退会する」をクリックしてください。
    </p>
  </div>

  <div class="row justify-content-center">
    <div class="col-2"><%= link_to "退会しない", edit_user_path(current_user), class: "btn btn-primary" %></div>
    <div class="col-2"><%= link_to "退会する", withdraw_path, method: :patch, class: "btn btn-danger", "data-confirm" => "退会しますか？" %></div>
  </div>

</div>