config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
scope module: :user do
  root 'homes#top'
  # タグの検索
  get "search_tag"=>"posts#search_tag"
  resources :users, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
  resources :messages, only: [:create,:destroy]
  resources :rooms, only: [:create,:show]
  resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy, :ranking] do
    collection do
      get :search
    end
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
end

get "users/:id/unsubscribe" => "user/users#unsubscribe", as: "unsubscribe"
patch "users/:id/withdraw" => "user/users#withdraw", as: "withdraw"


#ゲストログイン
devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  root 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:index, :show, :destroy] do
    resources :comments, only: [:destroy]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre, optional: true
  belongs_to :place, optional: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many :post_tags,dependent: :destroy
  has_many :tags,through: :post_tags
  validates :title, presence: true
  validates :text, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
end

def get_image
  (image.attached?) ? image : 'no_image.jpg'
end

def self.search(search)
  if Place.where('name LIKE ?', "#{search}%").present?
    joins(:place).where('places.name LIKE ?', "#{search}%")
  elsif search != ""
    where(['text LIKE(?) OR title LIKE(?) OR place_id LIKE(?)',"%#{search}%","%#{search}%","%#{search}%"])
  else
    Post.all
  end
end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    @post_all = Post.all
    @user = current_user

    @tag_list = Tag.all
    @users = User.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = @post.comments
    @post_tags = @post.tags
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  def update
    @post = Post.find(params[:id])

  end

  def search
    keyword = params[:keyword].sub(/　/,' ')  #全角であれば半角にする
    keywordAry = keyword.split(' ')# "ケーキ 青森県" → ["ケーキ", "青森県"]のように、『半角スペースを基準に分割する』
    # @posts = []
    @posts = Post.all
    keywordAry.each do |keyword|
      # @posts.concat(Post.search(keyword))
      @posts = @posts.search(keyword)
    end
    # @posts = @posts.uniq
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :place_id, :genre_id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image, :is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    post_comment = @post.comments.find(params[:id])
    post_comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end

  def index
    @user = current_user
    favorites = current_user.favorites.pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def create
    #formで送られてきたroom_idとcurrent_user.idを持ったデータがEntryにあるかを確認
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      #contentとroom_idはformで送られてきているため、user_idをマージして新規メッセージを作成
      @message = Message.create((message_params).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def message_params
      params.require(:message).permit(:user_id, :content, :room_id)
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @post = Post.new
  end

  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    @user = current_user
    @tag_list = Tag.all.limit(10)
    @post_all = Post.all
    if params[:place_id]
      # Post.find([1, 4, 2])
      @favorite_ranks = Post.where(id: Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id), place_id: params[:place_id]).limit(3)
    else
      @favorite_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
    if @post.user == current_user
      render "edit"
    else
      redirect_to post_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list=params[:post][:name].split(',')
    if @post.save
      @post.save_tag(tag_list)
      redirect_to posts_path(@post.id), notice:'投稿しました'
    else
      render:new, notice: '投稿に失敗しました'
    end
  end

  def update
    @post = Post.find(params[:id])
    tag_list=params[:post][:name].split(',')
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post.id), notice: '更新しました'
    else
       render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

 def search_tag
    @tag_list=Tag.all.order(created_at: :desc)
    @tag=Tag.find(params[:tag_id])
    @posts=@tag.posts.page(params[:page]).per(10)
  end

 def search
    keyword = params[:keyword].sub(/　/,' ')  #全角であれば半角にする
    keywordAry = keyword.split(' ')# "ケーキ 青森県" → ["ケーキ", "青森県"]のように、『半角スペースを基準に分割する』
    # @posts = []
    @posts = Post.all
    keywordAry.each do |keyword|
      # @posts.concat(Post.search(keyword))
      @posts = @posts.search(keyword)
    end
    # @posts = @posts.uniq
  end

 private
  def post_params
    params.require(:post).permit(:title, :text, :place_id, :genre_id, :image, :comment)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
   before_action :authenticate_user!

  def create
    @room = Room.create
    # current_userのEntry
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    # DMを受け取る側のEntry（users/showでuser_idは渡しているため、room_idを拾って、マージしている）
    @entry2 = Entry.create((entry_params).merge(room_id: @room.id))
    redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    # entriesテーブルにcurrent_user.idと紐付いたチャットルームがあるかどうか確認
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.order(created_at: :asc)
      @message = Message.new
      # チャットルームのユーザ情報を表示させるため代入
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end



  private
    def entry_params
      params.require(:entry).permit(:user_id, :room_id)
    end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  #ゲストログイン
  def guest_sign_in
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password])
      if @user.is_deleted == true
        redirect_to new_user_registration_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5)
    @post_all = @user.posts
    @favorites = Favorite.where(user_id: current_user.id)
    @currentUserEntry = Entry.where(user_id: current_user.id) # current_userをEntriesテーブルから探す
    @userEntry = Entry.where(user_id: @user.id) # DMを送る対象のユーザーをEntriesテーブルから探す
    if @user.id != current_user.id
      # currentUserと@userのEntriesをそれぞれ一つずつ取り出し、2人のroomが既に存在するかを確認
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
        # 2人のroomが既に存在していた場合
          if cu.room_id == u.room_id
            @isRoom = true
            #room_idを取り出す
            @roomId = cu.room_id
          end
        end
      end
      # 2人ののroomが存在しない場合
      unless @isRoom
        #roomとentryを新規に作成する
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user)
  end

  def unsubscribe
    @user = User.find_by(name: params[:name])
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image, :image)
  end

  def currect_user
    @user = User.find(params[:id])
    @user = @post.user
    redirect_to(root_path) unless @user == current_user
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/user/posts/edit.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-sm-3">
      <h3 class="text-info text-opacity-25">投稿内容編集</h3>
    </div>
    <%= form_with model: @post do |f| %>
      <div class="form-group">
        <%#= f.label :画像 %>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <p>タイトル</p>
        <p><%= f.text_field :title %></p>
      </div>

      <div class="form-group">
        <p>投稿文</p>
        <p><%= f.text_area :text %></p>
      </div>

      <div class="field">
        <%= f.label"タグ (,で区切ると複数タグ登録できます)" %>
        <%= f.text_field :name,value: @tag_list,class:"form-control"%>
      </div>

　    <div class="actions" style="margin:20px 0;">
        <%= f.submit "変更を保存",class:"btn btn-outline-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/posts/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-7">
      <h2 class="text-info text-opacity-25">投稿一覧</h2>
      <p>< <%= @posts.count %>件 / 全<%= @post_all.count %>件の投稿 ></p>
    </div>
    <div class="col-md-3 my-3">
      <%= link_to  new_post_path, class: "header-button btn btn-outline-success" do %>投稿する<i class="fas fa-pencil-alt"></i><% end %>
    </div>
    <div class="row my-2">
      <div class="col-md-9">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th class="border-dark table-active">投稿者</th>
              <th class="border-dark table-active">タイトル</th>
              <th class="border-dark table-active">投稿文</th>
              <th class="border-dark table-active">コメント</th>
              <th class="border-dark table-active">いいね</th>
              <th class="border-dark table-active">投稿日時</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td>
                  <%= link_to user_path(post.user.id) do %>
                    <%= image_tag post.user.get_profile_image, class: "rounded-circle", size: "40x40"  %>
                    <p><%= post.user.name %></p>
                  <% end %>
                </td>
                <td>
                  <%= link_to post_path(post.id) do %>
                    <%= post.title.truncate(10) %>
                  <% end %>
                </td>
                <td><%= post.text.truncate(13) %></td>
                <td><%= link_to "#{post.comments.count} 件", post_path(post.id) %></td>
                <td id='favorite_buttons_<%= post.id %>'>
                  <%= render 'user/favorites/favorites', post: post%>
                </td>
                <td><%= post.created_at.strftime('%Y/%m/%d  %H:%M') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div><%= paginate @posts %></div>
      </div>

      <div class="col-md-3">
        <!--タグリスト-->
        <table class="table table-bordered mt-3" style="width: 12rem;">
          <thead>
            <tr>
              <td class="table-active border-dark"><i class="fas fa-tag"></i>タグ検索</td>
            </tr>
          </thead>
          <tbody>
            <% @tag_list.each do |list|%>
              <tr>
                <td class="border-secondary">
                  <%=link_to list.name,search_tag_path(tag_id: list.id) %>
                  <%="(#{list.posts.count})" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="my-5">
          <h3>人気の投稿</h3>
          <%= form_with url: posts_path, method: :get, local: true do |f| %>
            <%= f.select :place_id, options_from_collection_for_select( Place.all, :id, :name), include_blank: "都道府県を選択" %>
            <%= f.submit "検索"%>

            <!--配列の1つ目から順に1位、２位と表示される-->
            <% @favorite_ranks.each.with_index(1) do |post, i| %>
              <p>👑第<%= i %>位</p>
              :
              <!--表示したいカラム-->
              <td>
                <%= link_to user_path(post.user.id) do %>
                  <%= image_tag post.user.get_profile_image, class: "rounded-circle", size: "40x40"  %>
                  <p><%= post.user.name %></p>
                <% end %>
                :タイトル
                <%= link_to post_path(post.id) do %>
  　               <%= post.title %>
                <% end %>
              </td>
            <%end%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/posts/new.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-sm-3">
      <h3 class="text-info text-opacity-25">投稿フォーム</h3>
      <%= render 'layouts/errors', obj: @post %>
      <%= form_with model:@post,local:true do |f| %>
        <div class="form-group">
        <%#= f.label :画像 %>
        <%#= f.file_field :images, multiple: true %>
        <%=f.file_field :image, acoept: "image/*" %>
        </div>

        <div class="form-group">
          <%= f.label :タイトル %>
          <%= f.text_field :title, class: 'form-control post_title' %>
        </div>
        <div class="form-group">
          <%= f.label :投稿文 %>
          <%= f.text_area :text, class: 'form-control post_body' %>
        </div>

        <div class="form-group">
          <%= f.label"タグ (,で区切ると複数タグ登録できます)" %>
          <%= f.text_field :name,value: @tag_list,class:"form-control"%>
        </div>

        <%= f.select :place_id, options_from_collection_for_select( Place.all, :id, :name),include_blank: "都道府県を選択" %>

        <div class="text-center">
          <%= f.submit "投稿", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/posts/search.html.erb
<div class="container">
  <div class="row my-4">
    <h2 class="text-info text-opacity-25">検索一覧『 <%= params[:keyword] %> 』</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th class="border-dark table-active">投稿者</th>
          <th class="border-dark table-active">タイトル</th>
          <th class="border-dark table-active">投稿文</th>
          <th class="border-dark table-active">コメント</th>
          <th class="border-dark table-active">いいね</th>
          <th class="border-dark table-active">投稿日時</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td>
              <%= link_to user_path(post.user.id) do %>
                <%= image_tag post.user.get_profile_image, class: "rounded-circle", size: "40x40"  %>
              <% end %>
            </td>
            <td>
              <%= link_to post_path(post.id) do %>
                <%= post.title %>
              <% end %>
            </td>
            <td><%= post.text %></td>
            <%#= post.place.name %>
            <td><%= link_to "#{post.comments.count} コメント", post_path(post.id) %></td>
            <td id='favorite_buttons_<%= post.id %>'>
              <%= render 'user/favorites/favorites', post: post%>
            </td>
            <td><%= post.created_at.strftime('%Y/%m/%d  %H:%M') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/user/posts/search_tag.html.erb
<div class="container">
  <h2 class="text-info text-opacity-25">タグが 『 <%= @tag.name %> 』 の投稿一覧</h2>

  <!--タグリスト-->
  <div>[その他のタグ]</div>
  <% @tag_list.each do |list|%>
    <%=link_to list.name,search_tag_path(tag_id: list.id) %>
    <%="(#{list.posts.count})" %>
  <% end %>
  <div class="row my-2">
    <div class="col-md-9">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th class="border-dark table-active">投稿者</th>
            <th class="border-dark table-active">タイトル</th>
            <th class="border-dark table-active">投稿文</th>
            <th class="border-dark table-active">コメント</th>
            <th class="border-dark table-active">いいね</th>
            <th class="border-dark table-active">投稿日時</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to user_path(post.user.id) do %>
                  <%= image_tag post.user.get_profile_image, class: "rounded-circle", size: "40x40"  %>
                  <p><%= post.user.name %></p>
                <% end %>
              </td>
              <td>
                <%=link_to post_path(post.id) do %>
                  <!--タイトル表示される文字数は２５文字までにしてます-->
                  <%= post.title.truncate(25) %>
                <% end %>
              </td>
              <td><%= post.text %></td>
              <td><%= link_to "#{post.comments.count} コメント", post_path(post.id) %></td>
              <td id='favorite_buttons_<%= post.id %>'>
                <%= render 'user/favorites/favorites', post: post%>
              </td>
              <td><%= post.created_at.strftime('%Y/%m/%d  %H:%M') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/user/posts/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-md-7"></div>
  </div>

  <div class="row">
    <div class="col-12">
      <!--タグ-->
      <% @post_tags.each do |tag| %>
      <%= link_to tag.name,search_tag_path(tag_id: tag.id)%>
      <%="(#{tag.posts.count})" %>
      <% end %>

      <h2 class="text-info text-opacity-25">投稿詳細画面</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-1 border-bottom">
      <%= link_to user_path(@post.user.id) do %>
        <%= image_tag @post.user.get_profile_image, class: "rounded-circle", size: "60x60"  %>
        <p><%= @post.user.name %></p>
      <% end %>
    </div>
    <div class="col-8 border-bottom mt-4">
      <h2>『<%= @post.title %>』</h2>
    </div>
    <div class="col-3 border-bottom mt-4">
      <% if @user == current_user %>
        <%= link_to "編集する",edit_post_path(@post.id), class: 'btn btn-outline-success' %>
        <%= link_to "投稿削除",post_path(@post.id),method: :delete, "data-confirm" => "本当に削除しますか？",class: 'btn btn-outline-danger' %>
      <% end %>
    </div>
  </div>

  <div class="row mx-5 mt-2">
    <h5><%= @post.text %></h5>
  </div>

  <div class="row mx-5 mt-2">
    <%= image_tag @post.get_image, size: "400x400" %>
  </div>

  <div class="row mx-5 mt-2">
    <p>場所：<%= @post.place.name %></p>
  </div>
  <div class="row mx-5 mt-2">
    <p>
      タグ：<% @post_tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </p>
  </div>
  <div class="row mx-5 mt-2">
    <p>投稿日時 :<%= @post.created_at.strftime('%Y/%m/%d  %H:%M') %></p>
  </div>

  <div class="row mx-5 mt-2">
    <div id='favorite_buttons_<%= @post.id %>'>
      <%=render 'user/favorites/favorites',post: @post%>
    </div>
  </div>

  <div class="row mx-5">
    <p>コメント件数：<%= @post.comments.count %></p>
  </div>

  <div class="row mx-5 mt-2">
    <table class="table table-sm">
      <tbody>
        <% @post.comments.each do |comment| %>
          <tr>
            <td>
              <%= image_tag comment.user.get_profile_image, class: "rounded-circle", size: "30x30" %>
              <p><%= comment.user.name %></p>
            </td>
            <td><%= comment.comment %> </td>
            <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
            <td>
              <% if comment.user_id == current_user.id %>
                <%= link_to 'コメントを削除', post_comment_path(@post,comment), data: {confirm: '本当に削除しますか？'}, method: :delete %>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row mx-5">
    <%= form_with model: [@post, @comment] do |f| %>
      <%= f.text_area :comment, rows: '3', placeholder: "コメントを入力する" %>
      <%= f.submit "送信する" %>
    <% end %>
  </div>
</div>